#!/bin/sh
DEVICE=$(bluetoothctl devices Connected)
DEVICE_NAME=$(echo $DEVICE | awk '{print $3}')
if [[ $DEVICE == "" ]]
then
    echo "%{F#888888} disconnected"
else
    echo "%{F#4287f5} %{F#ffffff}$DEVICE_NAME"
fi
