#!/bin/bash

while true
do
    i3-msg -t subscribe '[ "window" ]' >> /dev/null
    title=$(xdotool getwindowfocus getwindowname)
    window_class=$(xdotool getactivewindow getwindowclassname)

    if [[ $window_class == "firefox" ]]; then
	icon="%{F#e66000}%{T4}%{T-}%{F-}"
    elif [[ $window_class == "Emacs" ]]; then
	icon="%{F#ca6eff}%{T4}%{T-}%{F-}"
    elif [[ $window_class == "Zathura" ]]; then
	icon="%{F#6edbff}%{F-}"
    elif [[ $window_class == "Alacritty" ]]; then
	icon="%{F#42f569}%{F-}"
    elif [[ $window_class == "mpv" ]]; then
	icon="%{F#ff6e6e}%{F-}"
    elif [[ $window_class == "vlc" ]]; then
	icon="%{F#ff8400}嗢%{F-}"	
    else
	icon="%{F#ff6e6e}%{F-}"
    fi

    echo "${icon} %{F#aaffffff}%{T5}${title}"

done
