#!/bin/sh
# i3 wallpaper picker

wallpaper_path=$(find ~/wallpaper -type f | fzf-tmux -p -i --preview='feh --bg-scale {}')

[ -z "$wallpaper_path" ] || (echo "#!/bin/sh
feh --bg-scale $wallpaper_path" > ~/.config/i3/current_wallpaper)

