#!/bin/bash

while true
do
    i3-msg -t subscribe '[ "window" ]' >> /dev/null
    title=$(xdotool getwindowfocus getwindowname)

    if [[ $title == "i3" ]]; then
	icon=""
    elif [[ $title == *"Firefox"* ]]; then
	icon="%{F#e66000}%{T4}%{T-}%{F-}"
    elif [[ $title == *"Emacs"* ]]; then
	icon="%{F#ca6eff}%{T4}%{T-}%{F-}"
    elif [[ $title == *"pdf"* ]]; then
	icon="%{F#6edbff}%{F-}"
    elif [[ $title == *"@arch"* ]]; then
	icon="%{F#42f569}%{F-}"
    elif [[ $title == *"Spotify"* ]]; then
	icon="%{F#1db954}%{F-}"	
    else
	icon="%{F#ff6e6e}%{F-}"
    fi

    echo "${icon} %{F#aaffffff}${title}"

done
